### ISSUE TITLE
Continuous warnings generated if using latest version of PyTorch

### ISSUE THREAD

**Issue by tyler124** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On#72]
The following warning is generated if run using the latest version of PyTorch:
`UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.`

To fix, update the following line in dqn_basic.py:
`done_mask = torch.ByteTensor(dones).to(device)`

to:
`done_mask = torch.BoolTensor(dones).to(device)`

**Comment by Shmuma** [comment]
Hi!

It was raised couple of times: this repo was tested with pytorch 0.4 and won't be updated for latests pytorch versions, because it will require lots of testing to make sure everything is working. So, you have those options:
* install pytorch 0.4 and dependencies
* check examples from the second edition of the book (which has updated examples for pytorch 1.3): https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition

Wbr, Max
